### ISSUE TITLE
Wrong conversion for gain map

### ISSUE THREAD

**Issue by volodkuzn** [m13253/heif-hdrgainmap-decode#3]
There is a reference to hdr gain map extraction in Apple docs. You can see, how it can be implemented in python in the project below
https://github.com/johncf/apple-hdr-heic

**Comment by m13253** [comment]
Thanks for pointing out!

That code is more recent and seems more correct.
Since I started this project very early when there wasn’t enough documentation, it is highly likely my conversion is wrong — and I pointed out in my comments.

Maybe I will tell visitors of my project to use the other project instead.

**Comment by m13253** [comment]
I updated the Readme to point out to the other project. Thus closing.
